Fix compiler errors on Erlang >= 17
Licenser/dhcp pull request #3
Opened 2017-04-23 12:43 UTC by bfo

Since Erlang 17, there is no `erlang:now()` BIF. This change makes the
code use the new `erlang:timestamp()` where appropriate.

Used advice from https://stackoverflow.com/a/34028460.

2017-04-23 12:43 UTC, elvisci commented on src/dhcp_fsm.erl
>                                                      handler_state = State1}, Timeout};
Line 202 is too long:                                                     handler_state = State1}, Timeout};.

2017-04-23 12:43 UTC, elvisci commented on src/dhcp_fsm.erl
>                      Timeout = dhcp_package:get_option(ip_address_lease_time, RPkg),
Line 200 is too long:                     Timeout = dhcp_package:get_option(ip_address_lease_time, RPkg),.

2017-04-23 12:43 UTC, elvisci commented on src/dhcp_fsm.erl
>                                                        handler_state = State1}, ?S(To)};
Line 163 is too long:                                                       handler_state = State1}, ?S(To)};.

2017-04-23 12:43 UTC, elvisci commented on src/dhcp_fsm.erl
> +                    {ok, R, State#state{handler_state = S1, last=?CURRENT_TIME}};
Line 338 is too long:                     {ok, R, State#state{handler_state = S1, last=?CURRENT_TIME}};.

2017-04-23 12:43 UTC, elvisci commented on src/dhcp_fsm.erl
>                                                      handler_state = State1}, ?S(Timeout)};
Line 160 is too long:                                                     handler_state = State1}, ?S(Timeout)};.

2017-04-23 12:43 UTC, elvisci commented on src/dhcp_fsm.erl
>                      lager:error("[DHCP] invalid reply package for ~p:~p -> ~p", [M, F, R])
Line 340 is too long:                     lager:error("[DHCP] invalid reply package for ~p:~p -> ~p", [M, F, R]).

2017-04-23 12:43 UTC, elvisci commented on src/dhcp_fsm.erl
>                      Timeout = dhcp_package:get_option(ip_address_lease_time, dhcp_package:get_option(ip_address_lease_time, 3000, RPkg), Pkg),
Line 158 is too long:                     Timeout = dhcp_package:get_option(ip_address_lease_time, dhcp_package:get_option(ip_address_lease_time, 3000, RPkg), Pkg),.

2017-04-23 17:57 UTC, Licenser requested changes

2017-04-23 17:57 UTC, Licenser commented on include/dhcp.hrl
> +-ifdef(time_correction).
can we make this a function instead of a macro?

2017-04-23 21:24 UTC, elvisci commented on src/dhcp_fsm.erl
> +                    {ok, R, State#state{handler_state = S1, last=current_time()}};
Line 338 is too long:                     {ok, R, State#state{handler_state = S1, last=current_time()}};.

2017-04-23 21:24 UTC, elvisci commented on src/dhcp_fsm.erl
>                                                      handler_state = State1}, Timeout};
Line 202 is too long:                                                     handler_state = State1}, Timeout};.

2017-04-23 21:24 UTC, elvisci commented on src/dhcp_fsm.erl
>                      lager:error("[DHCP] invalid reply package for ~p:~p -> ~p", [M, F, R])
Line 340 is too long:                     lager:error("[DHCP] invalid reply package for ~p:~p -> ~p", [M, F, R]).

2017-04-23 21:24 UTC, elvisci commented on src/dhcp_fsm.erl
>                                                      handler_state = State1}, ?S(Timeout)};
Line 160 is too long:                                                     handler_state = State1}, ?S(Timeout)};.

2017-04-23 21:24 UTC, elvisci commented on src/dhcp_fsm.erl
>                                                        handler_state = State1}, ?S(To)};
Line 163 is too long:                                                       handler_state = State1}, ?S(To)};.

2017-04-23 22:16 UTC, Licenser approved these changes

2017-04-23 22:16 UTC, Licenser commented
Thanks mate :) looks good, I'll merge once the linter is happy!

2017-04-24 07:47 UTC, bfo commented on src/dhcp_fsm.erl
>                      Timeout = dhcp_package:get_option(ip_address_lease_time, RPkg),
Well, how long is too long?

2017-04-24 10:15 UTC, elvisci commented on src/dhcp_fsm.erl
> +		                                      ?S(To)};
Line 170 has a tab at column 0.

2017-04-24 10:15 UTC, elvisci commented on src/dhcp_fsm.erl
>      case  M:F(RPkg1, Pkg, State#state.handler_state) of
Remove the dynamic function call on line 334. Only modules that define callbacks should make dynamic calls.

2017-04-24 10:19 UTC, bfo commented on src/dhcp_fsm.erl
>      case  M:F(RPkg1, Pkg, State#state.handler_state) of
I'm afraid this is beyond me to fix.

2017-04-24 10:43 UTC, Licenser commented on src/dhcp_fsm.erl
>      case  M:F(RPkg1, Pkg, State#state.handler_state) of
no worries it's tricky, I'll fix that after the merge

2017-04-24 10:43 UTC, merged

2017-04-24 19:42 UTC, Licenser commented
Just noticed that the elvis errors where old :( sorry for ask you to fix my bad code style, didn't mean to do that. I thought I only had elvis enabled for repos that were clean to begin with.

I cleaned up the rest now and also updated it to use rebar3 and published a hex package.